name: Check Actions functional

on:
  push:

jobs:
  premake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Premake (local action)
        uses: ./premake-manager

      - name: Run premake-manager
        shell: bash
        run: premake-manager-cli
